### ISSUE TITLE
Java client library

### ISSUE THREAD

**Issue by phybros** [iamduo/workq#11]
I started porting your https://github.com/iamduo/go-workq repo into Java for fun. Check out https://github.com/phybros/workq-java

**Comment by iamduo** [comment]
@phybros thanks for contribution! I've added your client under the documentation for visibility (commit above). I'll also keep this issue open for a couple weeks to give it some more visibility in case others are looking for a Java client too.

**Comment by iamduo** [comment]
Closing now due to age. Thanks again for the contribution!
