### ISSUE TITLE
Sidekiq compatibility ?

### ISSUE THREAD

**Issue by gearnode** [iamduo/workq#2]
In your roadmap you have plan to render your lib compatible with Sidekiq (background worker in ruby) ?

**Comment by iamduo** [comment]
There is no roadmap item for Sidekiq integration. I don't know exactly how that would work too, I believe Sidekiq persists into Redis as a datastore using a Resque compatible message format. In Workq's case, it itself is the datastore and the client is just the connector to it. I believe you may be referring to just the Worker library API interface?

**Comment by iamduo** [comment]
Closing now due to age.
