### ISSUE TITLE
ActiveClients counting in server.go

### ISSUE THREAD

**Issue by danny-su** [iamduo/workq#8]
```
func (s *Server) clientLoop(c *client.Client) {
	atomic.AddUint64(&s.Usage.ActiveClients, 1)
	defer atomic.AddUint64(&s.Usage.ActiveClients, ^uint64(1))
```
The second line is incrementing ActiveClients by 1, but the third line is decrementing ActiveClients by 2 when leaving clientLoop method. Is that correct, or I missed something?
I think the following code is the right one:
`defer atomic.AddUint64(&s.Usage.ActiveClients, ^uint64(0))`

**Comment by iamduo** [comment]
Danny,
You didn't miss anything. This is a mistake and especially a mistake without a test case! I'll get it patched up covered with a test. Thanks.

**Comment by iamduo** [comment]
Issue resolved with tests covering. Thanks.
