### ISSUE TITLE
Does it support persistence?

### ISSUE THREAD

**Issue by chennqqi** [iamduo/workq#9]
Does it support persistence? 
When clients or server crashed or restart, Can the 'job' or 'work' in queue be restored?

**Comment by iamduo** [comment]
chennqqi,
At the moment there is no persistence, but it is on the official roadmap and is in progress.

**Comment by MrsJLane** [comment]
Persistance: the quality that allows someone to continue doing something or trying to do something even though it is difficult or opposed by other people... So I guess it's 2 or more factors

**Comment by iamduo** [comment]
@chennqqi @MrsJLane Persistence is now available in the latest [0.2.0 release](https://github.com/iamduo/workq/releases/tag/0.2.0)! Docs are available at [doc/cmdlog.md](https://github.com/iamduo/workq/blob/0.2.0/doc/cmdlog.md). Thank you for your patience.
